### ISSUE TITLE
Declaring a type with generics shows as a compilation error

### ISSUE THREAD

**Issue by jake-does-dev** [themartdev/intellij-gleam#17]
When declaring types with generics, it looks like a compilation error:

![image](https://github.com/user-attachments/assets/c1ad6906-b2e6-4ef5-8377-6818d4ea67bc)

I believe the expected behaviour is for this to not be an error, as `gleam test` runs as expected

Snippet taken from exercise: https://exercism.org/tracks/gleam/exercises/treasure-chest

**Comment by themartdev** [comment]
Thank you, will look into this!

**Comment by themartdev** [comment]
Fixed in [0.1.2](https://github.com/themartdev/intellij-gleam/releases/tag/0.1.2)
