### ISSUE TITLE
LSP4IJ discussion

### ISSUE THREAD

**Issue by angelozerr** [themartdev/intellij-gleam#22]
Hi,

I noticed that you are using LSP4IJ, it is great news!

Could you please create a PR at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#who-is-using-lsp4ij to ad your plugin please and add a review https://plugins.jetbrains.com/plugin/23257-lsp4ij/reviews if you like LSP4IJ to help us to promote LSP4IJ.

Add please see the 2 discussions:

 * https://github.com/redhat-developer/lsp4ij/discussions/558
 * https://github.com/redhat-developer/lsp4ij/discussions/541

Thanks!

**Comment by themartdev** [comment]
Great, I'm all for eliminating this hack if possible. I'll check it out. 
Do you know when 0.7.0 will be released with the `OSProcessStreamConnectionProvider`?

**Comment by angelozerr** [comment]
> Great, I'm all for eliminating this hack if possible. I'll check it out.

Thanks!

> Do you know when 0.7.0 will be released with the OSProcessStreamConnectionProvider?

OSProcessStreamConnectionProvider is hosted in 0.6.0 and I did this release this morning. We need towait for Jetbrains approvment (few days)

For 0.7.0 which will provide LSP API that you will need to avoid your hack, I don't know. The PR is not finished . Please follow the PR https://github.com/redhat-developer/lsp4ij/pull/543

**Comment by themartdev** [comment]
Gotcha, I'll keep an eye on it. Thanks for working on this!
